// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.retention-participant@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const RETENTION_PARTICIPANT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const RETENTION_PARTICIPANT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_retention_participant { () => { "{\"capability_id\":\"lenso.retention-participant@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"apply_retention\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_retention_participant_client { () => { "{\"capability_id\":\"lenso.retention-participant@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_retention_participant_client { () => { "{\"capability_id\":\"lenso.retention-participant@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const APPLY_RETENTION_OPERATION: &str = "apply_retention";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ApplyRetentionRequest {
    #[serde(rename = "action_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action_id: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: ApplyRetentionRequestMode,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ApplyRetentionRequestMode {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "anonymize")]
    Anonymize,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ApplyRetentionResponse {
    #[serde(rename = "receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ApplyRetentionError {
    Forbidden,
    InvalidRequest,
    UnsupportedMode,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct RetentionParticipant;
impl RequestCapability for RetentionParticipant {
    type Request = ApplyRetentionRequest;
    type Response = ApplyRetentionResponse;
    type DomainError = ApplyRetentionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != APPLY_RETENTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RetentionParticipantRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).apply_retention(context, request)
    }
}

impl serde::Serialize for ApplyRetentionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::UnsupportedMode => serializer.serialize_str("unsupported_mode"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ApplyRetentionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unsupported_mode" => Ok(Self::UnsupportedMode),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_apply_retention_request(value: &ApplyRetentionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_apply_retention_request(wire: &str) -> Result<ApplyRetentionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_apply_retention_response(value: &ApplyRetentionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_apply_retention_response(wire: &str) -> Result<ApplyRetentionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_apply_retention_error(value: &ApplyRetentionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_apply_retention_error(wire: &str) -> Result<ApplyRetentionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoRetentionParticipantApplyRetentionResult {
    fn __lenso_into_result(self) -> Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure>;
}
impl __LensoIntoRetentionParticipantApplyRetentionResult for Result<ApplyRetentionResponse, ApplyRetentionError> {
    fn __lenso_into_result(self) -> Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRetentionParticipantApplyRetentionResult for Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure> { self }
}
impl __LensoIntoRetentionParticipantApplyRetentionResult for Result<ApplyRetentionResponse, lenso_plugin_authoring::PluginError<ApplyRetentionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRetentionParticipantApplyRetentionResult for Result<ApplyRetentionResponse, RetentionParticipantInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ApplyRetentionResponse, ApplyRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RetentionParticipantInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RetentionParticipantInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait RetentionParticipantProvider: fmt::Debug + 'static {
    fn apply_retention(&self, context: InvocationContext, request: ApplyRetentionRequest) -> NativeRequestFuture<RetentionParticipant>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_retention_participant {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportRetentionParticipant;
        impl $crate::RetentionParticipantProvider for $plugin {
        fn apply_retention(&self, context: __LensoNativeSupportRetentionParticipant::InvocationContext, request: $crate::ApplyRetentionRequest) -> __LensoNativeSupportRetentionParticipant::NativeRequestFuture<$crate::RetentionParticipant> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::apply_retention(&plugin, context, request).await;
                $crate::__LensoIntoRetentionParticipantApplyRetentionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct RetentionParticipantRequestEndpoint { provider: Rc<dyn RetentionParticipantProvider> }

#[derive(Debug)]
pub struct RetentionParticipantEndpoint<P: RetentionParticipantProvider> { provider: Rc<P>, request_endpoint: RetentionParticipantRequestEndpoint }
impl<P: RetentionParticipantProvider> RetentionParticipantEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn RetentionParticipantProvider> = provider.clone();
        Self { provider, request_endpoint: RetentionParticipantRequestEndpoint { provider: request_provider } }
    }
}

impl<P: RetentionParticipantProvider> NativeRequestEndpoint for RetentionParticipantEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        APPLY_RETENTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            APPLY_RETENTION_OPERATION => {
                let Ok(request) = request.downcast::<ApplyRetentionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).apply_retention(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_retention_participant {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::RetentionParticipantEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_retention_participant {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_retention_participant!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct RetentionParticipantClient {
    apply_retention: NativeRequestHandle<RetentionParticipant>,
}
impl RetentionParticipantClient {
    pub fn new(handle: NativeRequestHandle<RetentionParticipant>) -> Self {
        Self { apply_retention: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn apply_retention(&self, request: ApplyRetentionRequest) -> Result<ApplyRetentionResponse, RetentionParticipantInvocationError> {
        self.apply_retention.invoke(APPLY_RETENTION_OPERATION, request).await
            .map_err(RetentionParticipantInvocationError::Runtime)?
            .map_err(RetentionParticipantInvocationError::Domain)
    }

    pub async fn apply_retention_with_context(&self, context: InvocationContext, request: ApplyRetentionRequest) -> Result<ApplyRetentionResponse, RetentionParticipantInvocationError> {
        self.apply_retention.invoke_with_context(APPLY_RETENTION_OPERATION, context, request).await
            .map_err(RetentionParticipantInvocationError::Runtime)?
            .map_err(RetentionParticipantInvocationError::Domain)
    }
}

impl CapabilityClient for RetentionParticipantClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            apply_retention: dependencies.one::<RetentionParticipant>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for RetentionParticipantClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    apply_retention: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RetentionParticipant>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetentionParticipantInvocationError {
    Domain(ApplyRetentionError),
    Runtime(RuntimeFailure),
}
