// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.retention-guard@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const RETENTION_GUARD_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const RETENTION_GUARD_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_retention_guard { () => { "{\"capability_id\":\"lenso.retention-guard@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"check_retention\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_retention_guard_client { () => { "{\"capability_id\":\"lenso.retention-guard@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_retention_guard_client { () => { "{\"capability_id\":\"lenso.retention-guard@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CHECK_RETENTION_OPERATION: &str = "check_retention";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CheckRetentionRequest {
    #[serde(rename = "action_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action_id: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: CheckRetentionRequestMode,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CheckRetentionRequestMode {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "anonymize")]
    Anonymize,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CheckRetentionResponse {
    #[serde(rename = "allowed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub allowed: bool,
    #[serde(rename = "decision_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision_id: String,
    #[serde(rename = "reason_code")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub reason_code: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CheckRetentionError {
    Forbidden,
    InvalidRequest,
    UnsupportedMode,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct RetentionGuard;
impl RequestCapability for RetentionGuard {
    type Request = CheckRetentionRequest;
    type Response = CheckRetentionResponse;
    type DomainError = CheckRetentionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CHECK_RETENTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<RetentionGuardRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).check_retention(context, request)
    }
}

impl serde::Serialize for CheckRetentionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::UnsupportedMode => serializer.serialize_str("unsupported_mode"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CheckRetentionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unsupported_mode" => Ok(Self::UnsupportedMode),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_check_retention_request(value: &CheckRetentionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_retention_request(wire: &str) -> Result<CheckRetentionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_check_retention_response(value: &CheckRetentionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_retention_response(wire: &str) -> Result<CheckRetentionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_check_retention_error(value: &CheckRetentionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_retention_error(wire: &str) -> Result<CheckRetentionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoRetentionGuardCheckRetentionResult {
    fn __lenso_into_result(self) -> Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure>;
}
impl __LensoIntoRetentionGuardCheckRetentionResult for Result<CheckRetentionResponse, CheckRetentionError> {
    fn __lenso_into_result(self) -> Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoRetentionGuardCheckRetentionResult for Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure> { self }
}
impl __LensoIntoRetentionGuardCheckRetentionResult for Result<CheckRetentionResponse, lenso_plugin_authoring::PluginError<CheckRetentionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoRetentionGuardCheckRetentionResult for Result<CheckRetentionResponse, RetentionGuardInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CheckRetentionResponse, CheckRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(RetentionGuardInvocationError::Domain(error)) => Ok(Err(error)),
            Err(RetentionGuardInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait RetentionGuardProvider: fmt::Debug + 'static {
    fn check_retention(&self, context: InvocationContext, request: CheckRetentionRequest) -> NativeRequestFuture<RetentionGuard>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_retention_guard {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportRetentionGuard;
        impl $crate::RetentionGuardProvider for $plugin {
        fn check_retention(&self, context: __LensoNativeSupportRetentionGuard::InvocationContext, request: $crate::CheckRetentionRequest) -> __LensoNativeSupportRetentionGuard::NativeRequestFuture<$crate::RetentionGuard> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::check_retention(&plugin, context, request).await;
                $crate::__LensoIntoRetentionGuardCheckRetentionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct RetentionGuardRequestEndpoint { provider: Rc<dyn RetentionGuardProvider> }

#[derive(Debug)]
pub struct RetentionGuardEndpoint<P: RetentionGuardProvider> { provider: Rc<P>, request_endpoint: RetentionGuardRequestEndpoint }
impl<P: RetentionGuardProvider> RetentionGuardEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn RetentionGuardProvider> = provider.clone();
        Self { provider, request_endpoint: RetentionGuardRequestEndpoint { provider: request_provider } }
    }
}

impl<P: RetentionGuardProvider> NativeRequestEndpoint for RetentionGuardEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CHECK_RETENTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CHECK_RETENTION_OPERATION => {
                let Ok(request) = request.downcast::<CheckRetentionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).check_retention(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_retention_guard {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::RetentionGuardEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_retention_guard {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_retention_guard!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct RetentionGuardClient {
    check_retention: NativeRequestHandle<RetentionGuard>,
}
impl RetentionGuardClient {
    pub fn new(handle: NativeRequestHandle<RetentionGuard>) -> Self {
        Self { check_retention: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn check_retention(&self, request: CheckRetentionRequest) -> Result<CheckRetentionResponse, RetentionGuardInvocationError> {
        self.check_retention.invoke(CHECK_RETENTION_OPERATION, request).await
            .map_err(RetentionGuardInvocationError::Runtime)?
            .map_err(RetentionGuardInvocationError::Domain)
    }

    pub async fn check_retention_with_context(&self, context: InvocationContext, request: CheckRetentionRequest) -> Result<CheckRetentionResponse, RetentionGuardInvocationError> {
        self.check_retention.invoke_with_context(CHECK_RETENTION_OPERATION, context, request).await
            .map_err(RetentionGuardInvocationError::Runtime)?
            .map_err(RetentionGuardInvocationError::Domain)
    }
}

impl CapabilityClient for RetentionGuardClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            check_retention: dependencies.one::<RetentionGuard>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for RetentionGuardClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    check_retention: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<RetentionGuard>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetentionGuardInvocationError {
    Domain(CheckRetentionError),
    Runtime(RuntimeFailure),
}
