// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.data-retention@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const DATA_RETENTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DATA_RETENTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_data_retention { () => { "{\"capability_id\":\"lenso.data-retention@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"execute_retention\",\"read_retention\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_data_retention_client { () => { "{\"capability_id\":\"lenso.data-retention@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_data_retention_client { () => { "{\"capability_id\":\"lenso.data-retention@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const EXECUTE_RETENTION_OPERATION: &str = "execute_retention";
pub const READ_RETENTION_OPERATION: &str = "read_retention";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteRetentionRequest {
    #[serde(rename = "action_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action_id: String,
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: RetentionMode,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetentionMode {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "anonymize")]
    Anonymize,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteRetentionResponse {
    #[serde(rename = "completed_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_count: i64,
    #[serde(rename = "pending_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub pending_count: i64,
    #[serde(rename = "rejected_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub rejected_count: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetentionStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetentionStatus {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "partial")]
    Partial,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExecuteRetentionError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRetentionRequest {
    #[serde(rename = "action_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub action_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRetentionResponse {
    #[serde(rename = "mode")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mode: RetentionMode,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "results")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub results: Vec<ReadRetentionResponseResultsItem>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetentionStatus,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRetentionResponseResultsItem {
    #[serde(rename = "provider_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_instance: String,
    #[serde(rename = "receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt: Option<String>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: RetentionParticipantStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetentionParticipantStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadRetentionError {
    Forbidden,
    InvalidRequest,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DataRetentionExecuteRetention;
impl RequestCapability for DataRetentionExecuteRetention {
    type Request = ExecuteRetentionRequest;
    type Response = ExecuteRetentionResponse;
    type DomainError = ExecuteRetentionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXECUTE_RETENTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataRetentionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).execute_retention(context, request)
    }
}

#[derive(Debug)]
pub struct DataRetentionReadRetention;
impl RequestCapability for DataRetentionReadRetention {
    type Request = ReadRetentionRequest;
    type Response = ReadRetentionResponse;
    type DomainError = ReadRetentionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_RETENTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataRetentionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_retention(context, request)
    }
}

impl serde::Serialize for ExecuteRetentionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExecuteRetentionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadRetentionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadRetentionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_execute_retention_request(value: &ExecuteRetentionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_retention_request(wire: &str) -> Result<ExecuteRetentionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_retention_response(value: &ExecuteRetentionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_retention_response(wire: &str) -> Result<ExecuteRetentionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_retention_error(value: &ExecuteRetentionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_retention_error(wire: &str) -> Result<ExecuteRetentionError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_retention_request(value: &ReadRetentionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_retention_request(wire: &str) -> Result<ReadRetentionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_retention_response(value: &ReadRetentionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_retention_response(wire: &str) -> Result<ReadRetentionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_retention_error(value: &ReadRetentionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_retention_error(wire: &str) -> Result<ReadRetentionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDataRetentionExecuteRetentionResult {
    fn __lenso_into_result(self) -> Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure>;
}
impl __LensoIntoDataRetentionExecuteRetentionResult for Result<ExecuteRetentionResponse, ExecuteRetentionError> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataRetentionExecuteRetentionResult for Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure> { self }
}
impl __LensoIntoDataRetentionExecuteRetentionResult for Result<ExecuteRetentionResponse, lenso_plugin_authoring::PluginError<ExecuteRetentionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataRetentionExecuteRetentionResult for Result<ExecuteRetentionResponse, DataRetentionExecuteRetentionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ExecuteRetentionResponse, ExecuteRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataRetentionExecuteRetentionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataRetentionExecuteRetentionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoDataRetentionReadRetentionResult {
    fn __lenso_into_result(self) -> Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure>;
}
impl __LensoIntoDataRetentionReadRetentionResult for Result<ReadRetentionResponse, ReadRetentionError> {
    fn __lenso_into_result(self) -> Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataRetentionReadRetentionResult for Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure> { self }
}
impl __LensoIntoDataRetentionReadRetentionResult for Result<ReadRetentionResponse, lenso_plugin_authoring::PluginError<ReadRetentionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataRetentionReadRetentionResult for Result<ReadRetentionResponse, DataRetentionReadRetentionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadRetentionResponse, ReadRetentionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataRetentionReadRetentionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataRetentionReadRetentionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DataRetentionProvider: fmt::Debug + 'static {
    fn execute_retention(&self, context: InvocationContext, request: ExecuteRetentionRequest) -> NativeRequestFuture<DataRetentionExecuteRetention>;
    fn read_retention(&self, context: InvocationContext, request: ReadRetentionRequest) -> NativeRequestFuture<DataRetentionReadRetention>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_data_retention {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDataRetention;
        impl $crate::DataRetentionProvider for $plugin {
        fn execute_retention(&self, context: __LensoNativeSupportDataRetention::InvocationContext, request: $crate::ExecuteRetentionRequest) -> __LensoNativeSupportDataRetention::NativeRequestFuture<$crate::DataRetentionExecuteRetention> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::execute_retention(&plugin, context, request).await;
                $crate::__LensoIntoDataRetentionExecuteRetentionResult::__lenso_into_result(result)
            })
        }
        fn read_retention(&self, context: __LensoNativeSupportDataRetention::InvocationContext, request: $crate::ReadRetentionRequest) -> __LensoNativeSupportDataRetention::NativeRequestFuture<$crate::DataRetentionReadRetention> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_retention(&plugin, context, request).await;
                $crate::__LensoIntoDataRetentionReadRetentionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct DataRetentionRequestEndpoint { provider: Rc<dyn DataRetentionProvider> }

#[derive(Debug)]
pub struct DataRetentionEndpoint<P: DataRetentionProvider> { provider: Rc<P>, request_endpoint: DataRetentionRequestEndpoint }
impl<P: DataRetentionProvider> DataRetentionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DataRetentionProvider> = provider.clone();
        Self { provider, request_endpoint: DataRetentionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DataRetentionProvider> NativeRequestEndpoint for DataRetentionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        EXECUTE_RETENTION_OPERATION,
        READ_RETENTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            EXECUTE_RETENTION_OPERATION => {
                let Ok(request) = request.downcast::<ExecuteRetentionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).execute_retention(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_RETENTION_OPERATION => {
                let Ok(request) = request.downcast::<ReadRetentionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_retention(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_data_retention {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DataRetentionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_data_retention {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_data_retention!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct DataRetentionClient {
    execute_retention: NativeRequestHandle<DataRetentionExecuteRetention>,
    read_retention: NativeRequestHandle<DataRetentionReadRetention>,
}
impl DataRetentionClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn execute_retention(&self, request: ExecuteRetentionRequest) -> Result<ExecuteRetentionResponse, DataRetentionExecuteRetentionInvocationError> {
        self.execute_retention.invoke(EXECUTE_RETENTION_OPERATION, request).await
            .map_err(DataRetentionExecuteRetentionInvocationError::Runtime)?
            .map_err(DataRetentionExecuteRetentionInvocationError::Domain)
    }

    pub async fn execute_retention_with_context(&self, context: InvocationContext, request: ExecuteRetentionRequest) -> Result<ExecuteRetentionResponse, DataRetentionExecuteRetentionInvocationError> {
        self.execute_retention.invoke_with_context(EXECUTE_RETENTION_OPERATION, context, request).await
            .map_err(DataRetentionExecuteRetentionInvocationError::Runtime)?
            .map_err(DataRetentionExecuteRetentionInvocationError::Domain)
    }

    pub async fn read_retention(&self, request: ReadRetentionRequest) -> Result<ReadRetentionResponse, DataRetentionReadRetentionInvocationError> {
        self.read_retention.invoke(READ_RETENTION_OPERATION, request).await
            .map_err(DataRetentionReadRetentionInvocationError::Runtime)?
            .map_err(DataRetentionReadRetentionInvocationError::Domain)
    }

    pub async fn read_retention_with_context(&self, context: InvocationContext, request: ReadRetentionRequest) -> Result<ReadRetentionResponse, DataRetentionReadRetentionInvocationError> {
        self.read_retention.invoke_with_context(READ_RETENTION_OPERATION, context, request).await
            .map_err(DataRetentionReadRetentionInvocationError::Runtime)?
            .map_err(DataRetentionReadRetentionInvocationError::Domain)
    }
}

impl CapabilityClient for DataRetentionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            execute_retention: dependencies.one::<DataRetentionExecuteRetention>()?,
            read_retention: dependencies.one::<DataRetentionReadRetention>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DataRetentionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    execute_retention: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataRetentionExecuteRetention>()?,
                    read_retention: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataRetentionReadRetention>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DataRetentionExecuteRetentionInvocationError {
    Domain(ExecuteRetentionError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DataRetentionReadRetentionInvocationError {
    Domain(ReadRetentionError),
    Runtime(RuntimeFailure),
}
