// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.data-export-source@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const DATA_EXPORT_SOURCE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DATA_EXPORT_SOURCE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_data_export_source { () => { "{\"capability_id\":\"lenso.data-export-source@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"collect_export\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_data_export_source_client { () => { "{\"capability_id\":\"lenso.data-export-source@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_data_export_source_client { () => { "{\"capability_id\":\"lenso.data-export-source@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const COLLECT_EXPORT_OPERATION: &str = "collect_export";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CollectExportRequest {
    #[serde(rename = "export_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub export_id: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CollectExportResponse {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<CollectExportResponseItemsItem>,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CollectExportResponseItemsItem {
    #[serde(rename = "item_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub item_name: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: String,
}

impl fmt::Debug for CollectExportResponseItemsItem {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CollectExportResponseItemsItem")
            .field("item_name", &self.item_name)
            .field("media_type", &self.media_type)
            .field("payload", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CollectExportError {
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DataExportSource;
impl RequestCapability for DataExportSource {
    type Request = CollectExportRequest;
    type Response = CollectExportResponse;
    type DomainError = CollectExportError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != COLLECT_EXPORT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataExportSourceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).collect_export(context, request)
    }
}

impl serde::Serialize for CollectExportError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CollectExportError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_collect_export_request(value: &CollectExportRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_collect_export_request(wire: &str) -> Result<CollectExportRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_collect_export_response(value: &CollectExportResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_collect_export_response(wire: &str) -> Result<CollectExportResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_collect_export_error(value: &CollectExportError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_collect_export_error(wire: &str) -> Result<CollectExportError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDataExportSourceCollectExportResult {
    fn __lenso_into_result(self) -> Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure>;
}
impl __LensoIntoDataExportSourceCollectExportResult for Result<CollectExportResponse, CollectExportError> {
    fn __lenso_into_result(self) -> Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataExportSourceCollectExportResult for Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure> { self }
}
impl __LensoIntoDataExportSourceCollectExportResult for Result<CollectExportResponse, lenso_plugin_authoring::PluginError<CollectExportError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataExportSourceCollectExportResult for Result<CollectExportResponse, DataExportSourceInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CollectExportResponse, CollectExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataExportSourceInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataExportSourceInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DataExportSourceProvider: fmt::Debug + 'static {
    fn collect_export(&self, context: InvocationContext, request: CollectExportRequest) -> NativeRequestFuture<DataExportSource>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_data_export_source {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDataExportSource;
        impl $crate::DataExportSourceProvider for $plugin {
        fn collect_export(&self, context: __LensoNativeSupportDataExportSource::InvocationContext, request: $crate::CollectExportRequest) -> __LensoNativeSupportDataExportSource::NativeRequestFuture<$crate::DataExportSource> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::collect_export(&plugin, context, request).await;
                $crate::__LensoIntoDataExportSourceCollectExportResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct DataExportSourceRequestEndpoint { provider: Rc<dyn DataExportSourceProvider> }

#[derive(Debug)]
pub struct DataExportSourceEndpoint<P: DataExportSourceProvider> { provider: Rc<P>, request_endpoint: DataExportSourceRequestEndpoint }
impl<P: DataExportSourceProvider> DataExportSourceEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DataExportSourceProvider> = provider.clone();
        Self { provider, request_endpoint: DataExportSourceRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DataExportSourceProvider> NativeRequestEndpoint for DataExportSourceEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        COLLECT_EXPORT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            COLLECT_EXPORT_OPERATION => {
                let Ok(request) = request.downcast::<CollectExportRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).collect_export(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_data_export_source {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DataExportSourceEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_data_export_source {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_data_export_source!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct DataExportSourceClient {
    collect_export: NativeRequestHandle<DataExportSource>,
}
impl DataExportSourceClient {
    pub fn new(handle: NativeRequestHandle<DataExportSource>) -> Self {
        Self { collect_export: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn collect_export(&self, request: CollectExportRequest) -> Result<CollectExportResponse, DataExportSourceInvocationError> {
        self.collect_export.invoke(COLLECT_EXPORT_OPERATION, request).await
            .map_err(DataExportSourceInvocationError::Runtime)?
            .map_err(DataExportSourceInvocationError::Domain)
    }

    pub async fn collect_export_with_context(&self, context: InvocationContext, request: CollectExportRequest) -> Result<CollectExportResponse, DataExportSourceInvocationError> {
        self.collect_export.invoke_with_context(COLLECT_EXPORT_OPERATION, context, request).await
            .map_err(DataExportSourceInvocationError::Runtime)?
            .map_err(DataExportSourceInvocationError::Domain)
    }
}

impl CapabilityClient for DataExportSourceClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            collect_export: dependencies.one::<DataExportSource>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DataExportSourceClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    collect_export: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataExportSource>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DataExportSourceInvocationError {
    Domain(CollectExportError),
    Runtime(RuntimeFailure),
}
