// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.data-export@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const DATA_EXPORT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const DATA_EXPORT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_data_export { () => { "{\"capability_id\":\"lenso.data-export@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"create_export\",\"purge_export\",\"read_export\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_data_export_client { () => { "{\"capability_id\":\"lenso.data-export@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_data_export_client { () => { "{\"capability_id\":\"lenso.data-export@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CREATE_EXPORT_OPERATION: &str = "create_export";
pub const PURGE_EXPORT_OPERATION: &str = "purge_export";
pub const READ_EXPORT_OPERATION: &str = "read_export";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateExportRequest {
    #[serde(rename = "export_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub export_id: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateExportResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "item_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub item_count: i64,
    #[serde(rename = "source_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_count: i64,
    #[serde(rename = "total_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub total_bytes: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateExportError {
    ArtifactTooLarge,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    SourceRejected,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PurgeExportRequest {
    #[serde(rename = "export_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub export_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PurgeExportResponse {
    #[serde(rename = "changed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub changed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PurgeExportError {
    Forbidden,
    InvalidRequest,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadExportRequest {
    #[serde(rename = "export_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub export_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadExportResponse {
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<ReadExportResponseItemsItem>,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadExportResponseItemsItem {
    #[serde(rename = "item_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub item_name: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: String,
    #[serde(rename = "provider_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_instance: String,
}

impl fmt::Debug for ReadExportResponseItemsItem {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ReadExportResponseItemsItem")
            .field("item_name", &self.item_name)
            .field("media_type", &self.media_type)
            .field("payload", &"<redacted>")
            .field("provider_instance", &self.provider_instance)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadExportError {
    Forbidden,
    InvalidRequest,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct DataExportCreateExport;
impl RequestCapability for DataExportCreateExport {
    type Request = CreateExportRequest;
    type Response = CreateExportResponse;
    type DomainError = CreateExportError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_EXPORT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataExportRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_export(context, request)
    }
}

#[derive(Debug)]
pub struct DataExportPurgeExport;
impl RequestCapability for DataExportPurgeExport {
    type Request = PurgeExportRequest;
    type Response = PurgeExportResponse;
    type DomainError = PurgeExportError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PURGE_EXPORT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataExportRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).purge_export(context, request)
    }
}

#[derive(Debug)]
pub struct DataExportReadExport;
impl RequestCapability for DataExportReadExport {
    type Request = ReadExportRequest;
    type Response = ReadExportResponse;
    type DomainError = ReadExportError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_EXPORT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<DataExportRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_export(context, request)
    }
}

impl serde::Serialize for CreateExportError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ArtifactTooLarge => serializer.serialize_str("artifact_too_large"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::SourceRejected => serializer.serialize_str("source_rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateExportError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "artifact_too_large" => Ok(Self::ArtifactTooLarge),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "source_rejected" => Ok(Self::SourceRejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for PurgeExportError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PurgeExportError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadExportError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadExportError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_create_export_request(value: &CreateExportRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_export_request(wire: &str) -> Result<CreateExportRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_export_response(value: &CreateExportResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_export_response(wire: &str) -> Result<CreateExportResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_export_error(value: &CreateExportError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_export_error(wire: &str) -> Result<CreateExportError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_purge_export_request(value: &PurgeExportRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_purge_export_request(wire: &str) -> Result<PurgeExportRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_purge_export_response(value: &PurgeExportResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_purge_export_response(wire: &str) -> Result<PurgeExportResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_purge_export_error(value: &PurgeExportError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_purge_export_error(wire: &str) -> Result<PurgeExportError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_export_request(value: &ReadExportRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_export_request(wire: &str) -> Result<ReadExportRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_export_response(value: &ReadExportResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_export_response(wire: &str) -> Result<ReadExportResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_export_error(value: &ReadExportError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_export_error(wire: &str) -> Result<ReadExportError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoDataExportCreateExportResult {
    fn __lenso_into_result(self) -> Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure>;
}
impl __LensoIntoDataExportCreateExportResult for Result<CreateExportResponse, CreateExportError> {
    fn __lenso_into_result(self) -> Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataExportCreateExportResult for Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure> { self }
}
impl __LensoIntoDataExportCreateExportResult for Result<CreateExportResponse, lenso_plugin_authoring::PluginError<CreateExportError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataExportCreateExportResult for Result<CreateExportResponse, DataExportCreateExportInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateExportResponse, CreateExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataExportCreateExportInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataExportCreateExportInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoDataExportPurgeExportResult {
    fn __lenso_into_result(self) -> Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure>;
}
impl __LensoIntoDataExportPurgeExportResult for Result<PurgeExportResponse, PurgeExportError> {
    fn __lenso_into_result(self) -> Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataExportPurgeExportResult for Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure> { self }
}
impl __LensoIntoDataExportPurgeExportResult for Result<PurgeExportResponse, lenso_plugin_authoring::PluginError<PurgeExportError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataExportPurgeExportResult for Result<PurgeExportResponse, DataExportPurgeExportInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PurgeExportResponse, PurgeExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataExportPurgeExportInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataExportPurgeExportInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoDataExportReadExportResult {
    fn __lenso_into_result(self) -> Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure>;
}
impl __LensoIntoDataExportReadExportResult for Result<ReadExportResponse, ReadExportError> {
    fn __lenso_into_result(self) -> Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoDataExportReadExportResult for Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure> { self }
}
impl __LensoIntoDataExportReadExportResult for Result<ReadExportResponse, lenso_plugin_authoring::PluginError<ReadExportError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoDataExportReadExportResult for Result<ReadExportResponse, DataExportReadExportInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadExportResponse, ReadExportError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(DataExportReadExportInvocationError::Domain(error)) => Ok(Err(error)),
            Err(DataExportReadExportInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait DataExportProvider: fmt::Debug + 'static {
    fn create_export(&self, context: InvocationContext, request: CreateExportRequest) -> NativeRequestFuture<DataExportCreateExport>;
    fn purge_export(&self, context: InvocationContext, request: PurgeExportRequest) -> NativeRequestFuture<DataExportPurgeExport>;
    fn read_export(&self, context: InvocationContext, request: ReadExportRequest) -> NativeRequestFuture<DataExportReadExport>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_data_export {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportDataExport;
        impl $crate::DataExportProvider for $plugin {
        fn create_export(&self, context: __LensoNativeSupportDataExport::InvocationContext, request: $crate::CreateExportRequest) -> __LensoNativeSupportDataExport::NativeRequestFuture<$crate::DataExportCreateExport> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_export(&plugin, context, request).await;
                $crate::__LensoIntoDataExportCreateExportResult::__lenso_into_result(result)
            })
        }
        fn purge_export(&self, context: __LensoNativeSupportDataExport::InvocationContext, request: $crate::PurgeExportRequest) -> __LensoNativeSupportDataExport::NativeRequestFuture<$crate::DataExportPurgeExport> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::purge_export(&plugin, context, request).await;
                $crate::__LensoIntoDataExportPurgeExportResult::__lenso_into_result(result)
            })
        }
        fn read_export(&self, context: __LensoNativeSupportDataExport::InvocationContext, request: $crate::ReadExportRequest) -> __LensoNativeSupportDataExport::NativeRequestFuture<$crate::DataExportReadExport> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_export(&plugin, context, request).await;
                $crate::__LensoIntoDataExportReadExportResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct DataExportRequestEndpoint { provider: Rc<dyn DataExportProvider> }

#[derive(Debug)]
pub struct DataExportEndpoint<P: DataExportProvider> { provider: Rc<P>, request_endpoint: DataExportRequestEndpoint }
impl<P: DataExportProvider> DataExportEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn DataExportProvider> = provider.clone();
        Self { provider, request_endpoint: DataExportRequestEndpoint { provider: request_provider } }
    }
}

impl<P: DataExportProvider> NativeRequestEndpoint for DataExportEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CREATE_EXPORT_OPERATION,
        PURGE_EXPORT_OPERATION,
        READ_EXPORT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CREATE_EXPORT_OPERATION => {
                let Ok(request) = request.downcast::<CreateExportRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_export(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PURGE_EXPORT_OPERATION => {
                let Ok(request) = request.downcast::<PurgeExportRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).purge_export(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_EXPORT_OPERATION => {
                let Ok(request) = request.downcast::<ReadExportRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_export(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_data_export {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::DataExportEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_data_export {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_data_export!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct DataExportClient {
    create_export: NativeRequestHandle<DataExportCreateExport>,
    purge_export: NativeRequestHandle<DataExportPurgeExport>,
    read_export: NativeRequestHandle<DataExportReadExport>,
}
impl DataExportClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn create_export(&self, request: CreateExportRequest) -> Result<CreateExportResponse, DataExportCreateExportInvocationError> {
        self.create_export.invoke(CREATE_EXPORT_OPERATION, request).await
            .map_err(DataExportCreateExportInvocationError::Runtime)?
            .map_err(DataExportCreateExportInvocationError::Domain)
    }

    pub async fn create_export_with_context(&self, context: InvocationContext, request: CreateExportRequest) -> Result<CreateExportResponse, DataExportCreateExportInvocationError> {
        self.create_export.invoke_with_context(CREATE_EXPORT_OPERATION, context, request).await
            .map_err(DataExportCreateExportInvocationError::Runtime)?
            .map_err(DataExportCreateExportInvocationError::Domain)
    }

    pub async fn purge_export(&self, request: PurgeExportRequest) -> Result<PurgeExportResponse, DataExportPurgeExportInvocationError> {
        self.purge_export.invoke(PURGE_EXPORT_OPERATION, request).await
            .map_err(DataExportPurgeExportInvocationError::Runtime)?
            .map_err(DataExportPurgeExportInvocationError::Domain)
    }

    pub async fn purge_export_with_context(&self, context: InvocationContext, request: PurgeExportRequest) -> Result<PurgeExportResponse, DataExportPurgeExportInvocationError> {
        self.purge_export.invoke_with_context(PURGE_EXPORT_OPERATION, context, request).await
            .map_err(DataExportPurgeExportInvocationError::Runtime)?
            .map_err(DataExportPurgeExportInvocationError::Domain)
    }

    pub async fn read_export(&self, request: ReadExportRequest) -> Result<ReadExportResponse, DataExportReadExportInvocationError> {
        self.read_export.invoke(READ_EXPORT_OPERATION, request).await
            .map_err(DataExportReadExportInvocationError::Runtime)?
            .map_err(DataExportReadExportInvocationError::Domain)
    }

    pub async fn read_export_with_context(&self, context: InvocationContext, request: ReadExportRequest) -> Result<ReadExportResponse, DataExportReadExportInvocationError> {
        self.read_export.invoke_with_context(READ_EXPORT_OPERATION, context, request).await
            .map_err(DataExportReadExportInvocationError::Runtime)?
            .map_err(DataExportReadExportInvocationError::Domain)
    }
}

impl CapabilityClient for DataExportClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            create_export: dependencies.one::<DataExportCreateExport>()?,
            purge_export: dependencies.one::<DataExportPurgeExport>()?,
            read_export: dependencies.one::<DataExportReadExport>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for DataExportClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    create_export: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataExportCreateExport>()?,
                    purge_export: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataExportPurgeExport>()?,
                    read_export: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<DataExportReadExport>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum DataExportCreateExportInvocationError {
    Domain(CreateExportError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DataExportPurgeExportInvocationError {
    Domain(PurgeExportError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum DataExportReadExportInvocationError {
    Domain(ReadExportError),
    Runtime(RuntimeFailure),
}
